<?php


use Illuminate\Database\Seeder;
use App\Models\Standard\Constituency;

class ConstituencyTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        Constituency::create(['name'  => 'Changamwe' ,  'county_id'  => '1']);
        Constituency::create(['name'  => 'Jomvu ' ,  'county_id'  => '1']);
        Constituency::create(['name'  => 'Kisauni' ,  'county_id'  => '1']);
        Constituency::create(['name'  => 'Nyali' ,  'county_id'  => '1']);
        Constituency::create(['name'  => 'Likoni   ' ,  'county_id'  => '1']);
        Constituency::create(['name'  => 'Mvita' ,  'county_id'  => '1']);
        Constituency::create(['name'  => 'Msambweni' ,  'county_id'  => '2']);
        Constituency::create(['name'  => 'Lunga' ,  'county_id'  => '2']);
        Constituency::create(['name'  => 'Matuga' ,  'county_id'  => '2']);
        Constituency::create(['name'  => 'Kinango' ,  'county_id'  => '2']);
        Constituency::create(['name'  => 'Kilifi North ' ,  'county_id'  => '3']);
        Constituency::create(['name'  => 'Kilifi South' ,  'county_id'  => '3']);
        Constituency::create(['name'  => 'Kaloleni' ,  'county_id'  => '3']);
        Constituency::create(['name'  => 'Rabai ' ,  'county_id'  => '3']);
        Constituency::create(['name'  => 'Ganze' ,  'county_id'  => '3']);
        Constituency::create(['name'  => 'Malindi  ' ,  'county_id'  => '3']);
        Constituency::create(['name'  => 'Magarini' ,  'county_id'  => '3']);
        Constituency::create(['name'  => 'Garsen' ,  'county_id'  => '4']);
        Constituency::create(['name'  => 'Galole' ,  'county_id'  => '4']);
        Constituency::create(['name'  => 'Bura' ,  'county_id'  => '4']);
        Constituency::create(['name'  => 'Lamu East' ,  'county_id'  => '5']);
        Constituency::create(['name'  => 'Lamu West' ,  'county_id'  => '5']);
        Constituency::create(['name'  => 'Taveta' ,  'county_id'  => '6']);
        Constituency::create(['name'  => 'Wundanyi' ,  'county_id'  => '6']);
        Constituency::create(['name'  => 'Mwatate' ,  'county_id'  => '6']);
        Constituency::create(['name'  => 'Voi' ,  'county_id'  => '6']);
        Constituency::create(['name'  => 'Dujis' ,  'county_id'  => '7']);
        Constituency::create(['name'  => 'Lagdera' ,  'county_id'  => '7']);
        Constituency::create(['name'  => 'Balambala' ,  'county_id'  => '7']);
        Constituency::create(['name'  => 'Dadaab ' ,  'county_id'  => '7']);
        Constituency::create(['name'  => 'Fafi' ,  'county_id'  => '7']);
        Constituency::create(['name'  => 'Ijara' ,  'county_id'  => '7']);
        Constituency::create(['name'  => 'Wajir North' ,  'county_id'  => '8']);
        Constituency::create(['name'  => 'Wajir East    ' ,  'county_id'  => '8']);
        Constituency::create(['name'  => 'Tarbaj' ,  'county_id'  => '8']);
        Constituency::create(['name'  => 'Wajir West' ,  'county_id'  => '8']);
        Constituency::create(['name'  => 'Eldas  ' ,  'county_id'  => '8']);
        Constituency::create(['name'  => 'Wajir South' ,  'county_id'  => '8']);
        Constituency::create(['name'  => 'Mandera West' ,  'county_id'  => '9']);
        Constituency::create(['name'  => 'Banissa ' ,  'county_id'  => '9']);
        Constituency::create(['name'  => 'Mandera North' , 'county_id'  => '9']);
        Constituency::create(['name'  => 'Mandera South' ,  'county_id'  => '9']);
        Constituency::create(['name'  => 'Mandera East' , 'county_id'  => '9']);
        Constituency::create(['name'  => 'Lafey ' ,  'county_id'  => '9']);
        Constituency::create(['name'  => 'Moyale' ,  'county_id'  => '10']);
        Constituency::create(['name'  => 'North Horr  ' ,  'county_id'  => '10']);
        Constituency::create(['name'  => 'Saku' ,  'county_id'  => '10']);
        Constituency::create(['name'  => 'Laisamis' ,  'county_id'  => '10']);
        Constituency::create(['name'  => 'Isiolo North' , 'county_id'  => '11']);
        Constituency::create(['name'  => 'Isiolo South ' ,  'county_id'  => '11']);
        Constituency::create(['name'  => 'Igembe South' , 'county_id'  => '12']);
        Constituency::create(['name'  => 'Igembe Central' , 'county_id'  => '12']);
        Constituency::create(['name'  => 'Igembe North' , 'county_id'  => '12']);
        Constituency::create(['name'  => 'Tigania West' , 'county_id'  => '12']);
        Constituency::create(['name'  => 'Tigania East ' ,  'county_id'  => '12']);
        Constituency::create(['name'  => 'North  Imenti' ,  'county_id'  => '12']);
        Constituency::create(['name'  => 'Mbuuri' ,  'county_id'  => '12']);
        Constituency::create(['name'  => 'Central Imenti' ,  'county_id'  => '12']);
        Constituency::create(['name'  => 'South Imenti' ,  'county_id'  => '12']);
        Constituency::create(['name'  => 'Nithi  ' ,  'county_id'  => '13']);
        Constituency::create(['name'  => 'Maara' ,  'county_id'  => '13']);
        Constituency::create(['name'  => 'Tharaka  ' ,  'county_id'  => '13']);
        Constituency::create(['name'  => 'Manyatta' ,  'county_id'  => '14']);
        Constituency::create(['name'  => 'Runyenjes    ' ,  'county_id'  => '14']);
        Constituency::create(['name'  => 'Gachoka' ,  'county_id'  => '14']);
        Constituency::create(['name'  => 'Siakago' ,  'county_id'  => '14']);
        Constituency::create(['name'  => 'Mwingi North' , 'county_id'  => '15']);
        Constituency::create(['name'  => 'Mwingi Central' , 'county_id'  => '15']);
        Constituency::create(['name'  => 'Mwingi South' , 'county_id'  => '15']);
        Constituency::create(['name'  => 'Kitui West    ' ,  'county_id'  => '15']);
        Constituency::create(['name'  => 'Kitui Rural' ,  'county_id'  => '15']);
        Constituency::create(['name'  => 'Kitui Centra' , 'county_id'  => '15']);
        Constituency::create(['name'  => 'Mutito' ,  'county_id'  => '15']);
        Constituency::create(['name'  => 'Kitui South  ' ,  'county_id'  => '15']);
        Constituency::create(['name'  => 'Masinga  ' ,  'county_id'  => '16']);
        Constituency::create(['name'  => 'Yatta    ' ,  'county_id'  => '16']);
        Constituency::create(['name'  => 'Kangundo' ,  'county_id'  => '16']);
        Constituency::create(['name'  => 'Matungulu ' ,  'county_id'  => '16']);
        Constituency::create(['name'  => 'Kathiani' ,  'county_id'  => '16']);
        Constituency::create(['name'  => 'Mavoko ' ,  'county_id'  => '16']);
        Constituency::create(['name'  => 'Machakos Town' , 'county_id'  => '16']);
        Constituency::create(['name'  => 'Mwala' ,  'county_id'  => '16']);
        Constituency::create(['name'  => 'Mbooni    ' ,  'county_id'  => '17']);
        Constituency::create(['name'  => 'Kilome' ,  'county_id'  => '17']);
        Constituency::create(['name'  => 'Kaiti' ,  'county_id'  => '17']);
        Constituency::create(['name'  => 'Makueni' ,  'county_id'  => '17']);
        Constituency::create(['name'  => 'Kibwezi West' , 'county_id'  => '17']);
        Constituency::create(['name'  => 'Kibwezi  East' , 'county_id'  => '17']);
        Constituency::create(['name'  => 'Kinangop  ' ,  'county_id'  => '18']);
        Constituency::create(['name'  => 'Kipipiri     ' ,  'county_id'  => '18']);
        Constituency::create(['name'  => 'Ol Kalou' ,  'county_id'  => '18']);
        Constituency::create(['name'  => 'Ol jorok   ' ,  'county_id'  => '18']);
        Constituency::create(['name'  => 'Ndaragwa' ,  'county_id'  => '18']);
        Constituency::create(['name'  => 'Tetu' ,  'county_id'  => '19']);
        Constituency::create(['name'  => 'Kieni' ,  'county_id'  => '19']);
        Constituency::create(['name'  => 'Mathira' ,  'county_id'  => '19']);
        Constituency::create(['name'  => 'Othaya' ,  'county_id'  => '19']);
        Constituency::create(['name'  => 'Mukurweini  ' ,  'county_id'  => '19']);
        Constituency::create(['name'  => 'Nyeri Town' ,  'county_id'  => '19']);
        Constituency::create(['name'  => 'Mwea' ,  'county_id'  => '20']);
        Constituency::create(['name'  => 'Gichugu' ,  'county_id'  => '20']);
        Constituency::create(['name'  => 'Ndia' ,  'county_id'  => '20']);
        Constituency::create(['name'  => 'Kirinyaga central' , 'county_id'  => '20']);
        Constituency::create(['name'  => 'Kangema' , 'county_id'  => '21']);
        Constituency::create(['name'  => 'Mathioya' , 'county_id'  => '21']);
        Constituency::create(['name'  => 'Kiharu' ,  'county_id'  => '21']);
        Constituency::create(['name'  => 'Kigumo' ,  'county_id'  => '21']);
        Constituency::create(['name'  => 'Maragwa' ,  'county_id'  => '21']);
        Constituency::create(['name'  => 'Kandara' ,  'county_id'  => '21']);
        Constituency::create(['name'  => 'Gatanga' ,  'county_id'  => '21']);
        Constituency::create(['name'  => 'Gatundu South' , 'county_id'  => '22']);
        Constituency::create(['name'  => 'Gatundu North' , 'county_id'  => '22']);
        Constituency::create(['name'  => 'Juja' ,  'county_id'  => '22']);
        Constituency::create(['name'  => 'Thika Town' ,  'county_id'  => '22']);
        Constituency::create(['name'  => 'Ruiru ' ,  'county_id'  => '22']);
        Constituency::create(['name'  => 'Githunguri' ,  'county_id'  => '22']);
        Constituency::create(['name'  => 'Kiambu' ,  'county_id'  => '22']);
        Constituency::create(['name'  => 'Kiambaa' ,  'county_id'  => '22']);
        Constituency::create(['name'  => 'Kabete' ,  'county_id'  => '22']);
        Constituency::create(['name'  => 'Kikuyu' ,  'county_id'  => '22']);
        Constituency::create(['name'  => 'Limuru' ,  'county_id'  => '22']);
        Constituency::create(['name'  => 'Lari' ,  'county_id'  => '22']);
        Constituency::create(['name'  => 'Turkana North' ,  'county_id'  => '23']);
        Constituency::create(['name'  => 'Turkana West' , 'county_id'  => '23']);
        Constituency::create(['name'  => 'Turkana Central' ,  'county_id'  => '23']);
        Constituency::create(['name'  => 'Loima' , 'county_id'  => '23']);
        Constituency::create(['name'  => 'Turkana South' ,  'county_id'  => '23']);
        Constituency::create(['name'  => 'Turkana East' ,  'county_id'  => '23']);
        Constituency::create(['name'  => 'Kapenguria' ,  'county_id'  => '24']);
        Constituency::create(['name'  => 'Sigor' ,  'county_id'  => '24']);
        Constituency::create(['name'  => 'Kacheliba' ,  'county_id'  => '24']);
        Constituency::create(['name'  => 'Pokot' ,  'county_id'  => '24']);
        Constituency::create(['name'  => 'Samburu West' ,  'county_id'  => '25']);
        Constituency::create(['name'  => 'Samburu North' , 'county_id'  => '25']);
        Constituency::create(['name'  => 'Samburu East' , 'county_id'  => '25']);
        Constituency::create(['name'  => 'Kwanza' ,  'county_id'  => '26']);
        Constituency::create(['name'  => 'Endebess ' ,  'county_id'  => '26']);
        Constituency::create(['name'  => 'Saboti' ,  'county_id'  => '26']);
        Constituency::create(['name'  => 'Kiminini ' ,  'county_id'  => '26']);
        Constituency::create(['name'  => 'Cherangani' ,  'county_id'  => '26']);
        Constituency::create(['name'  => 'Soy' ,  'county_id'  => '27']);
        Constituency::create(['name'  => 'Turbo' ,  'county_id'  => '27']);
        Constituency::create(['name'  => 'Moiben' ,  'county_id'  => '27']);
        Constituency::create(['name'  => 'Ainaboi ' ,  'county_id'  => '27']);
        Constituency::create(['name'  => 'Kapseret ' ,  'county_id'  => '27']);
        Constituency::create(['name'  => 'Tarakwa' ,  'county_id'  => '27']);
        Constituency::create(['name'  => 'Marakwet East' ,  'county_id'  => '28']);
        Constituency::create(['name'  => 'Marakwet West' ,  'county_id'  => '28']);
        Constituency::create(['name'  => 'Keiyo North' ,  'county_id'  => '28']);
        Constituency::create(['name'  => 'Keiyo South' ,  'county_id'  => '28']);
        Constituency::create(['name'  => 'Tinderet' ,  'county_id'  => '29']);
        Constituency::create(['name'  => 'Aldai' ,  'county_id'  => '29']);
        Constituency::create(['name'  => 'Nandi Hills' , 'county_id'  => '29']);
        Constituency::create(['name'  => 'Emgwen  North' ,  'county_id'  => '29']);
        Constituency::create(['name'  => 'Emgwen South' , 'county_id'  => '29']);
        Constituency::create(['name'  => 'Mosop' ,  'county_id'  => '29']);
        Constituency::create(['name'  => 'Baringo East' ,  'county_id'  => '30']);
        Constituency::create(['name'  => 'Baringo North' ,  'county_id'  => '30']);
        Constituency::create(['name'  => 'Baringo Central' ,  'county_id'  => '30']);
        Constituency::create(['name'  => 'Mochongoi' ,  'county_id'  => '30']);
        Constituency::create(['name'  => 'Mogotio' ,  'county_id'  => '30']);
        Constituency::create(['name'  => 'Eldama Ravine' ,  'county_id'  => '30']);
        Constituency::create(['name'  => 'Laikipia West' , 'county_id'  => '31']);
        Constituency::create(['name'  => 'Laikipia East' ,  'county_id'  => '31']);
        Constituency::create(['name'  => 'Laikipia North' , 'county_id'  => '31']);
        Constituency::create(['name'  => 'Molo' ,  'county_id'  => '32']);
        Constituency::create(['name'  => 'Njoro ' ,  'county_id'  => '32']);
        Constituency::create(['name'  => 'Naivasha' ,  'county_id'  => '32']);
        Constituency::create(['name'  => 'Gilgil ' ,  'county_id'  => '32']);
        Constituency::create(['name'  => 'Kuresoi South' ,  'county_id'  => '32']);
        Constituency::create(['name'  => 'Kuresoi North' , 'county_id'  => '32']);
        Constituency::create(['name'  => 'Subukia' ,  'county_id'  => '32']);
        Constituency::create(['name'  => 'Rongai' ,  'county_id'  => '32']);
        Constituency::create(['name'  => 'Bahati ' ,  'county_id'  => '32']);
        Constituency::create(['name'  => 'Nakuru Town West' , 'county_id'  => '32']);
        Constituency::create(['name'  => 'Nakuru Town East' , 'county_id'  => '32']);
        Constituency::create(['name'  => 'Kilgoris' ,  'county_id'  => '33']);
        Constituency::create(['name'  => 'Emurua Dikirr' ,  'county_id'  => '33']);
        Constituency::create(['name'  => 'Narok North' ,  'county_id'  => '33']);
        Constituency::create(['name'  => 'Narok East ' ,  'county_id'  => '33']);
        Constituency::create(['name'  => 'Narok South' ,  'county_id'  => '33']);
        Constituency::create(['name'  => 'Narok West ' ,  'county_id'  => '33']);
        Constituency::create(['name'  => 'Kajiado North' ,  'county_id'  => '34']);
        Constituency::create(['name'  => 'Kajiado Central' ,  'county_id'  => '34']);
        Constituency::create(['name'  => 'Kajiado East' , 'county_id'  => '34']);
        Constituency::create(['name'  => 'Kajiado West' , 'county_id'  => '34']);
        Constituency::create(['name'  => 'Kajiado South' ,  'county_id'  => '34']);
        Constituency::create(['name'  => 'Kipkelion     East' ,  'county_id'  => '35']);
        Constituency::create(['name'  => 'Kipkelion West ' ,  'county_id'  => '35']);
        Constituency::create(['name'  => 'Ainamoi' ,  'county_id'  => '35']);
        Constituency::create(['name'  => 'Bureti' ,  'county_id'  => '35']);
        Constituency::create(['name'  => 'Belgut' ,  'county_id'  => '35']);
        Constituency::create(['name'  => 'Sigowet' ,  'county_id'  => '35']);
        Constituency::create(['name'  => 'Sotik' ,  'county_id'  => '36']);
        Constituency::create(['name'  => 'Chepalungu' ,  'county_id'  => '36']);
        Constituency::create(['name'  => 'Bomet East ' ,  'county_id'  => '36']);
        Constituency::create(['name'  => 'Bomet Central ' ,  'county_id'  => '36']);
        Constituency::create(['name'  => 'Konoin' ,  'county_id'  => '36']);
        Constituency::create(['name'  => 'Lugari' ,  'county_id'  => '37']);
        Constituency::create(['name'  => 'Likuyani' ,  'county_id'  => '37']);
        Constituency::create(['name'  => 'Malava' ,  'county_id'  => '37']);
        Constituency::create(['name'  => 'Lurambi' ,  'county_id'  => '37']);
        Constituency::create(['name'  => 'Navakholo' ,  'county_id'  => '37']);
        Constituency::create(['name'  => 'Mumias' ,  'county_id'  => '37']);
        Constituency::create(['name'  => 'Mumias  East' , 'county_id'  => '37']);
        Constituency::create(['name'  => 'Matungu' ,  'county_id'  => '37']);
        Constituency::create(['name'  => 'Butere' ,  'county_id'  => '37']);
        Constituency::create(['name'  => 'Khwisero' ,  'county_id'  => '37']);
        Constituency::create(['name'  => 'Shinyalu' ,  'county_id'  => '37']);
        Constituency::create(['name'  => 'Ikolomani' ,  'county_id'  => '37']);
        Constituency::create(['name'  => 'Vihiga' ,  'county_id'  => '38']);
        Constituency::create(['name'  => 'Sabatia' ,  'county_id'  => '38']);
        Constituency::create(['name'  => 'Hamisi' ,  'county_id'  => '38']);
        Constituency::create(['name'  => 'Emuhaya' ,  'county_id'  => '38']);
        Constituency::create(['name'  => 'Luanda' ,  'county_id'  => '38']);
        Constituency::create(['name'  => 'Mt. Elgon' ,  'county_id'  => '39']);
        Constituency::create(['name'  => 'Sirisia' ,  'county_id'  => '39']);
        Constituency::create(['name'  => 'Kabuchai' ,  'county_id'  => '39']);
        Constituency::create(['name'  => 'Bumula' ,  'county_id'  => '39']);
        Constituency::create(['name'  => 'Kanduyi' ,  'county_id'  => '39']);
        Constituency::create(['name'  => 'Webuye' ,  'county_id'  => '39']);
        Constituency::create(['name'  => 'Bokoli' ,  'county_id'  => '39']);
        Constituency::create(['name'  => 'Kimilili' ,  'county_id'  => '39']);
        Constituency::create(['name'  => 'Tongaren' ,  'county_id'  => '39']);
        Constituency::create(['name'  => 'Teso North' ,  'county_id'  => '40']);
        Constituency::create(['name'  => 'Teso South' ,  'county_id'  => '40']);
        Constituency::create(['name'  => 'Nambale' ,  'county_id'  => '40']);
        Constituency::create(['name'  => 'Matayos' ,  'county_id'  => '40']);
        Constituency::create(['name'  => 'Butula' ,  'county_id'  => '40']);
        Constituency::create(['name'  => 'Funyula' ,  'county_id'  => '40']);
        Constituency::create(['name'  => 'Budalangi' ,  'county_id'  => '40']);
        Constituency::create(['name'  => 'Ugenya' ,  'county_id'  => '41']);
        Constituency::create(['name'  => 'Ugunja' ,  'county_id'  => '41']);
        Constituency::create(['name'  => 'Alego Usonga' ,  'county_id'  => '41']);
        Constituency::create(['name'  => 'Gem' ,  'county_id'  => '41']);
        Constituency::create(['name'  => 'Bondo' ,  'county_id'  => '41']);
        Constituency::create(['name'  => 'Rarieda' ,  'county_id'  => '41']);
        Constituency::create(['name'  => 'Kisumu East' , 'county_id'  => '42']);
        Constituency::create(['name'  => 'Kisumu West' ,  'county_id'  => '42']);
        Constituency::create(['name'  => 'Kisumu Central' , 'county_id'  => '42']);
        Constituency::create(['name'  => 'Seme' ,  'county_id'  => '42']);
        Constituency::create(['name'  => 'Nyando' ,  'county_id'  => '42']);
        Constituency::create(['name'  => 'Muhoroni' ,  'county_id'  => '42']);
        Constituency::create(['name'  => 'Nyakach' ,  'county_id'  => '42']);
        Constituency::create(['name'  => 'Kasipul  ' ,  'county_id'  => '43']);
        Constituency::create(['name'  => 'Kabondo' ,  'county_id'  => '43']);
        Constituency::create(['name'  => 'Karachuonyo' ,  'county_id'  => '43']);
        Constituency::create(['name'  => 'Rangwe' ,  'county_id'  => '43']);
        Constituency::create(['name'  => 'Homa Bay Town ' ,  'county_id'  => '43']);
        Constituency::create(['name'  => 'Ndhiwa' ,  'county_id'  => '43']);
        Constituency::create(['name'  => 'Mbita' ,  'county_id'  => '43']);
        Constituency::create(['name'  => 'Gwasi' ,  'county_id'  => '43']);
        Constituency::create(['name'  => 'Rongo' ,  'county_id'  => '44']);
        Constituency::create(['name'  => 'Awendo' ,  'county_id'  => '44']);
        Constituency::create(['name'  => 'Migori East  ' ,  'county_id'  => '44']);
        Constituency::create(['name'  => 'Migori West' ,  'county_id'  => '44']);
        Constituency::create(['name'  => 'Uriri' ,  'county_id'  => '44']);
        Constituency::create(['name'  => 'Nyatike' ,  'county_id'  => '44']);
        Constituency::create(['name'  => 'Kuria  East   ' ,  'county_id'  => '44']);
        Constituency::create(['name'  => 'Kuria West' ,  'county_id'  => '44']);
        Constituency::create(['name'  => 'Bonchari' ,  'county_id'  => '45']);
        Constituency::create(['name'  => ' South' ,  'county_id'  => '45']);
        Constituency::create(['name'  => ' Bomachoge' ,  'county_id'  => '45']);
        Constituency::create(['name'  => ' Bobasi' ,  'county_id'  => '45']);
        Constituency::create(['name'  => ' Gucha' ,  'county_id'  => '45']);
        Constituency::create(['name'  => ' Nyaribari Masaba' , 'county_id'  => '45']);
        Constituency::create(['name'  => 'Nyaribari Chache' ,  'county_id'  => '45']);
        Constituency::create(['name'  => ' Marani' ,  'county_id'  => '45']);
        Constituency::create(['name'  => 'Mosocho' ,  'county_id'  => '45']);
        Constituency::create(['name'  => 'Kitutu Msasaba' , 'county_id'  => '46']);
        Constituency::create(['name'  => 'West Mugirango' , 'county_id'  => '46']);
        Constituency::create(['name'  => 'North Mugirango' , 'county_id'  => '46']);
        Constituency::create(['name'  => 'Borabu' ,  'county_id'  => '46']);
        Constituency::create(['name'  => 'Westlands' ,  'county_id'  => '47']);
        Constituency::create(['name'  => 'Kawangware' , 'county_id'  => '47']);
        Constituency::create(['name'  => 'Dagoretti' ,  'county_id'  => '47']);
        Constituency::create(['name'  => 'Karen-Langata' , 'county_id'  => '47']);
        Constituency::create(['name'  => 'Kibra' , 'county_id'  => '47']);
        Constituency::create(['name'  => 'Kasarani' ,  'county_id'  => '47']);
        Constituency::create(['name'  => 'Roysambu' ,  'county_id'  => '47']);
        Constituency::create(['name'  => 'Ruaraka ' ,  'county_id'  => '47']);
        Constituency::create(['name'  => 'Embakasi' ,  'county_id'  => '47']);
        Constituency::create(['name'  => 'Kariobangi' ,  'county_id'  => '47']);
        Constituency::create(['name'  => 'Kayole' , 'county_id'  => '47']);
        Constituency::create(['name'  => 'Mihango ' ,  'county_id'  => '47']);
        Constituency::create(['name'  => 'Umoja ' ,  'county_id'  => '47']);
        Constituency::create(['name'  => 'Makadara' ,  'county_id'  => '47']);
        Constituency::create(['name'  => 'Kamukunji' ,  'county_id'  => '47']);
        Constituency::create(['name'  => 'Starehe' ,  'county_id'  => '47']);
        Constituency::create(['name'  => 'Mathare ' ,  'county_id'  => '47']);

    }
}
